services:
  mongo-database:
    image: mongo:7.0.0
    container_name: mongo-database
    ports:
    - "4002:27017"
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: password

  auth-backend:
    image: backend-service
    build:
      context: ./P465-Tour-Management-BE
      dockerfile: Dockerfile
    container_name: auth-backend
    ports:
    - "3000:3000"
    restart: always
    environment:
      - DB=mongodb://127.0.0.1:4002/
    network_mode: "host"

  place-backend:
    image: place-service
    build:
      context: ./P465-Tour-Management-Place-BE
      dockerfile: Dockerfile
    container_name: place-backend
    ports:
    - "3001:3002"
    restart: always
    environment:
      - DB=mongodb://127.0.0.1:4002/
    network_mode: "host"
    
  